# Generated by Django 4.2.14 on 2024-07-22 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип подразделения')),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.unit', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.unittype', verbose_name='Тип подразделения'),
        ),
    ]
